/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import AppSystem.Network;
import Enterprise.Enterprise;
import Organization.Organization;
import Person.Person;
import UserAccount.UserAccount;
import UserAccount.UserAccountDirectory;
import WorkAreas.EnterpriseManagerRole;
import WorkAreas.ProductOrganizationManagerRole;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siqiyang
 */
public class EnterpriseManagementJPanel extends javax.swing.JPanel {
    private Network appSystem;
    private UserAccount useraccount;
    DefaultTableModel viewtableModel;
    Enterprise enterprise;
    Organization organization;    
    /**
     * Creates new form EnterpriseManagementJPanel
     */
    public EnterpriseManagementJPanel(Network appSystem, Enterprise enterprise, Organization organization,UserAccount useraccount) {
        initComponents();
        this.setVisible(true);


        this.appSystem = appSystem;
        this.useraccount = useraccount;
        this.enterprise = enterprise;
        this.organization = organization;        
        this.viewtableModel = (DefaultTableModel) jTable1.getModel();
        
        tablePopulate();    
        populateEnterprise();
        
       
    }
    
    public void populateEnterprise() {   
        enterprisenNameBox.addItem("Convenience");
        enterprisenNameBox.addItem("Health");
        enterprisenNameBox.addItem("Connection");
        enterprisenNameBox.addItem("Legal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addEnterpriseManagerBtn = new javax.swing.JButton();
        DeleteEnterpriseBtn = new javax.swing.JButton();
        enterprisenNameBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        updateEnterpriseBtn = new javax.swing.JButton();
        updateNameField = new javax.swing.JTextField();
        updatePasswordTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 800));
        setSize(new java.awt.Dimension(1300, 800));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Enterprise Name", "User ID", "Manager Name", "Username", "Password"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        addEnterpriseManagerBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addEnterpriseManagerBtn.setForeground(new java.awt.Color(236, 100, 44));
        addEnterpriseManagerBtn.setText("Add Enterprise Manager");
        addEnterpriseManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseManagerBtnActionPerformed(evt);
            }
        });

        DeleteEnterpriseBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        DeleteEnterpriseBtn.setForeground(new java.awt.Color(236, 100, 44));
        DeleteEnterpriseBtn.setText("Delete Enterprise Manager");
        DeleteEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEnterpriseBtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(236, 100, 44));
        jLabel1.setText("Enterprise Name: ");

        jLabel2.setForeground(new java.awt.Color(236, 100, 44));
        jLabel2.setText("Manager Name:");

        jLabel3.setForeground(new java.awt.Color(236, 100, 44));
        jLabel3.setText("User Name:");

        jLabel4.setForeground(new java.awt.Color(236, 100, 44));
        jLabel4.setText("Password");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        updateEnterpriseBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        updateEnterpriseBtn.setForeground(new java.awt.Color(236, 100, 44));
        updateEnterpriseBtn.setText("Update Enterprise Manager");
        updateEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEnterpriseBtnActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(236, 100, 44));
        jLabel5.setText("Update Manager Name:");

        jLabel6.setForeground(new java.awt.Color(236, 100, 44));
        jLabel6.setText("Update Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(addEnterpriseManagerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(DeleteEnterpriseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(updateEnterpriseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameField)
                                    .addComponent(enterprisenNameBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usernameField)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updatePasswordTextField)
                                    .addComponent(updateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterprisenNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEnterpriseManagerBtn)
                    .addComponent(DeleteEnterpriseBtn)
                    .addComponent(updateEnterpriseBtn))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(381, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEnterpriseManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseManagerBtnActionPerformed
        // TODO add your handling code here:
//        Enterprise enterprise = this.appSystem.getEnterprises().createEnterprise(enterpriseField.getText(), (String) typeComboBox.getSelectedItem());
//
//        JOptionPane.showMessageDialog(null, "Enterprise Created");
//        displayEnterpriseInfo();
        Boolean foundDuplicate = false;
        System.out.print("found dup is set to false");

        for(Enterprise enterprise: this.appSystem.getEnterprises().getEnterpiseList()){
            UserAccountDirectory ua = enterprise.getUseraccountDirectory();
        
            if(ua.accountExists(usernameField.getText(), passwordField.getText())) {
                foundDuplicate = true;
                System.out.print("found dup at enterprise level");
                JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
                break;
            }
            
        }
        UserAccountDirectory ua = this.appSystem.getTopLevelUserAccountDirectory();
        if(ua.accountExists(usernameField.getText(), passwordField.getText())) {
            foundDuplicate = true;
            System.out.print("found dup at app level");
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
        }
        if(foundDuplicate == false) {
            Enterprise e = this.appSystem.getEnterprises().findEnterprise((String) enterprisenNameBox.getSelectedItem());
            System.out.print(e.getUseraccountDirectory().getUserAccountList().size());
//            System.out.println(e.getEnterpriseAdmin().getUserName());
            if(e.getEnterpriseAdmin()==null){
                Person p = appSystem.getPersonDirectory().createPerson(nameField.getText());
                UserAccount user= e.getUseraccountDirectory().createUserAccount(usernameField.getText(), passwordField.getText(), new EnterpriseManagerRole());
                user.setPerson(p); 
                e.setEnterpriseAdmin(user);
                JOptionPane.showMessageDialog(null, "Manager created");
            }else{
                JOptionPane.showMessageDialog(null, "Manager exists");
            }
            
            

            tablePopulate();
        }
    }//GEN-LAST:event_addEnterpriseManagerBtnActionPerformed

    private void DeleteEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEnterpriseBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        UserAccount u = (UserAccount) jTable1.getValueAt(selectedRow, 1);
        Enterprise e = (Enterprise) jTable1.getValueAt(selectedRow, 0);
        e.getUseraccountDirectory().deleteEnterpriseManager(u);
        this.appSystem.getTopLevelUserAccountDirectory().deleteEnterpriseManager(u);
        e.setEnterpriseAdmin(null);
//        System.out.println("======================");
//        System.out.println(e.getUseraccountDirectory().getUserAccountList());

        if (this.appSystem.getTopLevelUserAccountDirectory().getUserAccountList().size()>0){
            tablePopulate();
        }else{
            viewtableModel.setRowCount(0);
        }

    }//GEN-LAST:event_DeleteEnterpriseBtnActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void updateEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEnterpriseBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        UserAccount u = (UserAccount) jTable1.getValueAt(selectedRow, 1);
        u.getPerson().setName(updateNameField.getText());
        u.setPassword(updatePasswordTextField.getText());
         tablePopulate();
        
    }//GEN-LAST:event_updateEnterpriseBtnActionPerformed
    public void  tablePopulate() {
        
        ArrayList<Enterprise> enterprises = this.appSystem.getEnterprises().getEnterpiseList();
        
        if(enterprises != null){
            viewtableModel.setRowCount(0);
            for (Enterprise e : enterprises){
                if(e.getUseraccountDirectory() != null && e.getUseraccountDirectory().getUserAccountList() != null){
                for(UserAccount u: e.getUseraccountDirectory().getUserAccountList()){
                    if(u.getRole().getRoleType().equals("Enterprise Manager")){
                        Object row[] = new Object[5];
                        row[0] = e;
                        row[1] =u;
                        row[2] = u.getPerson().getName();
                        row[3] = u.getUserName();
                        row[4] = u.getPassword();


                        viewtableModel.addRow(row);
                    }
                }
            }
          } 
        } else {
            System.out.print("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteEnterpriseBtn;
    private javax.swing.JButton addEnterpriseManagerBtn;
    private javax.swing.JComboBox<String> enterprisenNameBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton updateEnterpriseBtn;
    private javax.swing.JTextField updateNameField;
    private javax.swing.JTextField updatePasswordTextField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

}
