/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import AppSystem.Network;
import Enterprise.Enterprise;
import Organization.Organization;
import Organization.ProductManagement.OrderItem;
import Organization.ProductManagement.Product;
import Organization.ProductManagement.ProductCart;
import Organization.ProductManagement.ProductCatalog;
import Organization.ProductManagement.ProductOrder;
import Organization.ProductOrganization;
import Person.Client.Client;
import Requests.ConvenienceRequest;
import Requests.DeliveryRequest;
import Requests.Request;
import Requests.RequestDirectory;
import Requests.ServiceRequest;
import UserAccount.UserAccount;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khatna
 */
public class MyRequests extends javax.swing.JPanel {

    /**
     * Creates new form MyRequests
     */
    private Network appSystem;
    private UserAccount useraccount;
    DefaultTableModel viewtableModel;
    Enterprise enterprise;
    Organization organization;  
    DefaultTableModel viewTableModel;
    boolean isDelivery = false;
    boolean isConvenience = false;
    boolean isService = false;
    DefaultListModel<String> prescriptionListModel;
    public MyRequests(Network appSystem, Enterprise enterprise, Organization organization,UserAccount useraccount) {
        initComponents();
        this.setSize(1120,800);
        this.setVisible(true);
        this.appSystem = appSystem;
        this.useraccount = useraccount;
        this.enterprise = enterprise;
        this.organization = organization;   
        this.viewTableModel = (DefaultTableModel) jTable1.getModel();
        switch (this.useraccount.getRole().getRoleType()) {
            case "Convenience Volunteer":
                displayMyDeliveryRequests();
                break;
            case "Healthcare Specialist":
            case "Legal Specialist":
                displayMyServiceRequests();
                break;
            default:
                displayMyConvenienceRequests();
                break;
        }
        jLayeredPane1.removeAll();


        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        healthPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        reqID1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        reqRequester1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        reqDate1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        reqStatus1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        healthReqCompleteBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        healthResponderComment = new javax.swing.JTextArea();
        createConvenienceRequestBtn = new javax.swing.JButton();
        prescriptionCombo = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        prescriptionList = new javax.swing.JList<>();
        removeBtnPrescriptionList = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        healthReqDetails = new javax.swing.JTextArea();
        legalAndConnectionPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        reqID2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        reqRequester2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        reqDate2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        reqStatus2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        legalConnCompleteBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        legalConnResponderComments = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        legalConnReqDetails = new javax.swing.JTextArea();
        deliveryPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reqID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reqRequester = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reqDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        reqStatus = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        reqLocation = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deliveryCompleteBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        deliveryReqResponderComment = new javax.swing.JTextArea();
        conveniencePanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        reqID3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        reqRequester3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        reqDate3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        reqStatus3 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        convCompleteBtn = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        convenienceReqResponderComment = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 800));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestID", "Requester", "Request Date", "Request Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        healthPanel.setBackground(new java.awt.Color(153, 153, 153));
        healthPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Request Details", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        healthPanel.setPreferredSize(new java.awt.Dimension(910, 540));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Request ID");

        reqID1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqID1.setForeground(new java.awt.Color(255, 255, 255));
        reqID1.setText("jLabel1");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Requester");

        reqRequester1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqRequester1.setForeground(new java.awt.Color(255, 255, 255));
        reqRequester1.setText("jLabel1");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Request Date");

        reqDate1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqDate1.setForeground(new java.awt.Color(255, 255, 255));
        reqDate1.setText("jLabel1");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Request Status");

        reqStatus1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqStatus1.setForeground(new java.awt.Color(255, 255, 255));
        reqStatus1.setText("jLabel1");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Available prescriptions");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Request Details");

        healthReqCompleteBtn.setForeground(new java.awt.Color(236, 100, 44));
        healthReqCompleteBtn.setText("Mark Complete");
        healthReqCompleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthReqCompleteBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Leave a message to the requestor (if any)");

        healthResponderComment.setColumns(20);
        healthResponderComment.setRows(5);
        jScrollPane4.setViewportView(healthResponderComment);

        createConvenienceRequestBtn.setForeground(new java.awt.Color(236, 100, 44));
        createConvenienceRequestBtn.setText("Create pharmacy request");
        createConvenienceRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConvenienceRequestBtnActionPerformed(evt);
            }
        });

        prescriptionCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prescriptionComboMouseClicked(evt);
            }
        });

        jScrollPane5.setViewportView(prescriptionList);

        removeBtnPrescriptionList.setForeground(new java.awt.Color(236, 100, 44));
        removeBtnPrescriptionList.setText("Remove from list");
        removeBtnPrescriptionList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnPrescriptionListActionPerformed(evt);
            }
        });

        healthReqDetails.setColumns(20);
        healthReqDetails.setRows(5);
        jScrollPane6.setViewportView(healthReqDetails);

        javax.swing.GroupLayout healthPanelLayout = new javax.swing.GroupLayout(healthPanel);
        healthPanel.setLayout(healthPanelLayout);
        healthPanelLayout.setHorizontalGroup(
            healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(healthPanelLayout.createSequentialGroup()
                        .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqID1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqRequester1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(healthPanelLayout.createSequentialGroup()
                        .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(jScrollPane5)
                                .addComponent(prescriptionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeBtnPrescriptionList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel13))
                        .addGap(78, 78, 78)
                        .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(healthPanelLayout.createSequentialGroup()
                                .addComponent(createConvenienceRequestBtn)
                                .addGap(15, 15, 15)
                                .addComponent(healthReqCompleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 108, Short.MAX_VALUE))
        );
        healthPanelLayout.setVerticalGroup(
            healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, healthPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(healthPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(healthPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqRequester1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(healthPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqID1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(healthPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(healthPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4)))
                .addGap(18, 18, 18)
                .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(healthPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prescriptionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeBtnPrescriptionList))
                    .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(healthReqCompleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createConvenienceRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        jLayeredPane1.add(healthPanel, "card3");

        legalAndConnectionPanel.setBackground(new java.awt.Color(153, 153, 153));
        legalAndConnectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Request Details", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Request ID");

        reqID2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqID2.setForeground(new java.awt.Color(255, 255, 255));
        reqID2.setText("jLabel1");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Requester");

        reqRequester2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqRequester2.setForeground(new java.awt.Color(255, 255, 255));
        reqRequester2.setText("jLabel1");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Request Date");

        reqDate2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqDate2.setForeground(new java.awt.Color(255, 255, 255));
        reqDate2.setText("jLabel1");

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Request Status");

        reqStatus2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqStatus2.setForeground(new java.awt.Color(255, 255, 255));
        reqStatus2.setText("jLabel1");

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Request details");

        legalConnCompleteBtn.setText("Mark Complete");
        legalConnCompleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legalConnCompleteBtnActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Leave a message to the requestor (if any)");

        legalConnResponderComments.setColumns(20);
        legalConnResponderComments.setRows(5);
        jScrollPane7.setViewportView(legalConnResponderComments);

        legalConnReqDetails.setColumns(20);
        legalConnReqDetails.setRows(5);
        jScrollPane8.setViewportView(legalConnReqDetails);

        javax.swing.GroupLayout legalAndConnectionPanelLayout = new javax.swing.GroupLayout(legalAndConnectionPanel);
        legalAndConnectionPanel.setLayout(legalAndConnectionPanelLayout);
        legalAndConnectionPanelLayout.setHorizontalGroup(
            legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                        .addGroup(legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqID2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqRequester2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addGroup(legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 171, Short.MAX_VALUE))
                    .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(80, 80, 80))
                            .addComponent(legalConnCompleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        legalAndConnectionPanelLayout.setVerticalGroup(
            legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, legalAndConnectionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqRequester2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqID2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(legalAndConnectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(legalAndConnectionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8)))
                .addGap(27, 27, 27)
                .addComponent(legalConnCompleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jLayeredPane1.add(legalAndConnectionPanel, "card2");

        deliveryPanel.setBackground(new java.awt.Color(153, 153, 153));
        deliveryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Request Details", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Request ID");

        reqID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqID.setForeground(new java.awt.Color(255, 255, 255));
        reqID.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Requester");

        reqRequester.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqRequester.setForeground(new java.awt.Color(255, 255, 255));
        reqRequester.setText("jLabel1");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Request Date");

        reqDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqDate.setForeground(new java.awt.Color(255, 255, 255));
        reqDate.setText("jLabel1");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Request Status");

        reqStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqStatus.setForeground(new java.awt.Color(255, 255, 255));
        reqStatus.setText("jLabel1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Delivery includes the product items below");

        reqLocation.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqLocation.setForeground(new java.awt.Color(255, 255, 255));
        reqLocation.setText("jLabel1");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Delivery Location");

        deliveryCompleteBtn.setText("Mark Complete");
        deliveryCompleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryCompleteBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Leave a message to the requestor (if any)");

        deliveryReqResponderComment.setColumns(20);
        deliveryReqResponderComment.setRows(5);
        jScrollPane3.setViewportView(deliveryReqResponderComment);

        javax.swing.GroupLayout deliveryPanelLayout = new javax.swing.GroupLayout(deliveryPanel);
        deliveryPanel.setLayout(deliveryPanelLayout);
        deliveryPanelLayout.setHorizontalGroup(
            deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addComponent(reqLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(deliveryPanelLayout.createSequentialGroup()
                                    .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(reqID, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(56, 56, 56)
                                    .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(reqRequester, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deliveryPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reqDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reqStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(deliveryCompleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57))))))
        );
        deliveryPanelLayout.setVerticalGroup(
            deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqRequester, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deliveryCompleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jLayeredPane1.add(deliveryPanel, "card4");

        conveniencePanel.setBackground(new java.awt.Color(153, 153, 153));
        conveniencePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Request Details", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Request ID");

        reqID3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqID3.setForeground(new java.awt.Color(255, 255, 255));
        reqID3.setText("jLabel1");

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Requester");

        reqRequester3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqRequester3.setForeground(new java.awt.Color(255, 255, 255));
        reqRequester3.setText("jLabel1");

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Request Date");

        reqDate3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqDate3.setForeground(new java.awt.Color(255, 255, 255));
        reqDate3.setText("jLabel1");

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Request Status");

        reqStatus3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reqStatus3.setForeground(new java.awt.Color(255, 255, 255));
        reqStatus3.setText("jLabel1");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(jList2);

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Request order includes the items below");

        convCompleteBtn.setText("Mark Complete");
        convCompleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convCompleteBtnActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Leave a message to the requestor (if any)");

        convenienceReqResponderComment.setColumns(20);
        convenienceReqResponderComment.setRows(5);
        jScrollPane10.setViewportView(convenienceReqResponderComment);

        javax.swing.GroupLayout conveniencePanelLayout = new javax.swing.GroupLayout(conveniencePanel);
        conveniencePanel.setLayout(conveniencePanelLayout);
        conveniencePanelLayout.setHorizontalGroup(
            conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conveniencePanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(conveniencePanelLayout.createSequentialGroup()
                        .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqID3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqRequester3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane9))
                .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conveniencePanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reqStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conveniencePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(convCompleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))))
        );
        conveniencePanelLayout.setVerticalGroup(
            conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conveniencePanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conveniencePanelLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(conveniencePanelLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(conveniencePanelLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqRequester3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(conveniencePanelLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reqID3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100)
                .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(conveniencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addComponent(convCompleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLayeredPane1.add(conveniencePanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int selectedR = jTable1.getSelectedRow();
       
        RequestDirectory reqDir = appSystem.getReqDir();


         DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
         
        if(isDelivery){
            DeliveryRequest selectedRequest = (DeliveryRequest) reqDir.findRequestById(jTable1.getValueAt(selectedR, 0).toString());
            jLayeredPane1.removeAll();
            jLayeredPane1.add(deliveryPanel);
           jLayeredPane1.repaint();
           jLayeredPane1.revalidate();

            reqID.setText(selectedRequest.getRequestID());
            reqRequester.setText(selectedRequest.getRequester().getPerson().getName());
            String dateStr = format.format(selectedRequest.getRequestDate());
            reqDate.setText(dateStr);
            reqStatus.setText(selectedRequest.getStatus());
            
            ProductOrder po = selectedRequest.getOrderToBedelivered();
            DefaultListModel<String> listModel = new DefaultListModel<String>();
            for(OrderItem oi: po.getProductsPurchased()){
                listModel.addElement(oi.getSelectedProduct().getName());
            }
            jList1.setModel(listModel);

            reqLocation.setText(selectedRequest.getDeliveryAddress());
            
        }
        if(isService){
            
            ServiceRequest serviceRequest = (ServiceRequest) reqDir.findRequestById(jTable1.getValueAt(selectedR, 0).toString());
            if(serviceRequest.getServiceOrder().getOrg().getName().equals("Hospital")){
                jLayeredPane1.removeAll();
                jLayeredPane1.add(healthPanel);
               jLayeredPane1.repaint();
               jLayeredPane1.revalidate();
                reqID1.setText(serviceRequest.getRequestID());
                reqRequester1.setText(serviceRequest.getRequester().getPerson().getName());
                String dateStr = format.format(serviceRequest.getRequestDate());
                reqDate1.setText(dateStr);
                reqStatus1.setText(serviceRequest.getStatus());
                
                healthReqDetails.setText(serviceRequest.getRequestDetails());
                ProductOrganization pharm = (ProductOrganization) this.appSystem.getEnterprises().findEnterprise("Convenience").getOrganizationDirectory().findOrganization("Pharmacy");
                ProductCatalog pcat = pharm.getProductCatalog();
                for(Product p : pcat.getAllProducts()){
                    prescriptionCombo.addItem(p.getName());
                }                   
            }else{
                
                jLayeredPane1.removeAll();
                jLayeredPane1.add(legalAndConnectionPanel);
                jLayeredPane1.repaint();
                jLayeredPane1.revalidate();
                reqID2.setText(serviceRequest.getRequestID());
                reqRequester2.setText(serviceRequest.getRequester().getPerson().getName());
                String dateStr = format.format(serviceRequest.getRequestDate());
                reqDate2.setText(dateStr);
                reqStatus2.setText(serviceRequest.getStatus());
                legalConnReqDetails.setText(serviceRequest.getRequestDetails());
            }

            
        }
            if(isConvenience){
                ConvenienceRequest convRequest = (ConvenienceRequest) reqDir.findRequestById(jTable1.getValueAt(selectedR, 0).toString());
                jLayeredPane1.removeAll();
                jLayeredPane1.add(conveniencePanel);
                jLayeredPane1.repaint();
                jLayeredPane1.revalidate();
                reqID3.setText(convRequest.getRequestID());
                reqRequester3.setText(convRequest.getRequester().getPerson().getName());
                String dateStr = format.format(convRequest.getRequestDate());
                reqDate3.setText(dateStr);
                reqStatus3.setText(convRequest.getStatus());
                
                ProductOrder po = convRequest.getProductOrder();
                DefaultListModel<String> listModel = new DefaultListModel<String>();
                for(OrderItem oi: po.getProductsPurchased()){
                    listModel.addElement(oi.getSelectedProduct().getName());
                }
                jList2.setModel(listModel);
            }
        
//        if(serviceRequest.getServiceOrder().getOrg().getName().equals("Pharmacy")){
//               
//            
//            }

    }//GEN-LAST:event_jTable1MouseClicked

    private void healthReqCompleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthReqCompleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedR = jTable1.getSelectedRow();

        RequestDirectory reqDir = appSystem.getReqDir();
       ServiceRequest serviceRequest = (ServiceRequest) reqDir.findRequestById(jTable1.getValueAt(selectedR, 0).toString());
        
        String responderComment = healthResponderComment.getText();
        
        if(!responderComment.isEmpty()){
            serviceRequest.setResponderComments(responderComment);
        }
        serviceRequest.processRequest();
        viewTableModel.setValueAt("Completed", selectedR, 3);
        JOptionPane.showMessageDialog(null, "Thank you for your time and care!");
    }//GEN-LAST:event_healthReqCompleteBtnActionPerformed

    private void legalConnCompleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legalConnCompleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedR = jTable1.getSelectedRow();

        RequestDirectory reqDir = appSystem.getReqDir();
        ServiceRequest serviceRequest = (ServiceRequest) reqDir.findRequestById(jTable1.getValueAt(selectedR, 0).toString());
        
        String responderComment = legalConnResponderComments.getText();
        
        if(!responderComment.isEmpty()){
            serviceRequest.setResponderComments(responderComment);
        }
        serviceRequest.processRequest();
        viewTableModel.setValueAt("Completed", selectedR, 3);
        JOptionPane.showMessageDialog(null, "Thank you for your time and care!");
    }//GEN-LAST:event_legalConnCompleteBtnActionPerformed

    private void deliveryCompleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryCompleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedR = jTable1.getSelectedRow();

        RequestDirectory reqDir = appSystem.getReqDir();
        DeliveryRequest selectedRequest = (DeliveryRequest) reqDir.findRequestById(jTable1.getValueAt(selectedR, 0).toString());
        
        String responderComment = deliveryReqResponderComment.getText();
        
        if(!responderComment.isEmpty()){
            selectedRequest.setResponderComments(responderComment);
        }
        selectedRequest.processRequest();
        viewTableModel.setValueAt("Completed", selectedR, 3);
        JOptionPane.showMessageDialog(null, "Thank you for your time and care!");
    }//GEN-LAST:event_deliveryCompleteBtnActionPerformed

    private void prescriptionComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prescriptionComboMouseClicked
        // TODO add your handling code here:
        String selectedItem =  prescriptionCombo.getSelectedItem().toString();
        prescriptionListModel = new DefaultListModel<String>();
        prescriptionListModel.addElement(selectedItem);
        prescriptionList.setModel(prescriptionListModel);
    }//GEN-LAST:event_prescriptionComboMouseClicked

    private void removeBtnPrescriptionListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnPrescriptionListActionPerformed
        // TODO add your handling code here:
        int selectedIndex = prescriptionList.getSelectedIndex();
         if (selectedIndex != -1) {
                    prescriptionListModel.remove(selectedIndex);
                }
    }//GEN-LAST:event_removeBtnPrescriptionListActionPerformed

    private void createConvenienceRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConvenienceRequestBtnActionPerformed
        // TODO add your handling code here:
//        ArrayList<Product> prodOrder = new ArrayList();
         int selectedR = jTable1.getSelectedRow();
       
        RequestDirectory reqDir = appSystem.getReqDir();
        ProductCart pharmCart = new ProductCart();
        ProductOrganization pharm = (ProductOrganization) this.appSystem.getEnterprises().findEnterprise("Convenience").getOrganizationDirectory().findOrganization("Pharmacy");
        ProductCatalog pcat = pharm.getProductCatalog();
        ArrayList<OrderItem> orderItems = new ArrayList();

        for (int i = 0; i < prescriptionListModel.getSize(); i++) {
            String item = prescriptionListModel.getElementAt(i);
            
            Product p = pcat.findProductByName(item);
            OrderItem oi = new OrderItem(p,1);

            orderItems.add(oi);
        }
        pharmCart.setCartOrderItems(orderItems);
        ServiceRequest serviceRequest = (ServiceRequest) reqDir.findRequestById(jTable1.getValueAt(selectedR, 0).toString());
        ProductOrder po = pharmCart.processCart((Client) serviceRequest.getRequester().getPerson(),pharm);
        reqDir.createConvenienceRequest(serviceRequest.getRequester(), po);
        JOptionPane.showMessageDialog(null, "New pharmacy order is placed with selected items!");
    }//GEN-LAST:event_createConvenienceRequestBtnActionPerformed

    private void convCompleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convCompleteBtnActionPerformed
        // TODO add your handling code here:
         int selectedR = jTable1.getSelectedRow();

        RequestDirectory reqDir = appSystem.getReqDir();
        
        ConvenienceRequest convRequest = (ConvenienceRequest) reqDir.findRequestById(jTable1.getValueAt(selectedR, 0).toString());
        
        String responderComment = convenienceReqResponderComment.getText();
        
        if(!responderComment.isEmpty()){
            convRequest.setResponderComments(responderComment);
//            selectedRequest.setStatus("Completed");
        }
        convRequest.processRequest();
        DeliveryRequest delreq = reqDir.createDeliveryRequest(convRequest.getRequester(), convRequest.getProductOrder());
        JOptionPane.showMessageDialog(null, "Thank you for your time, a new delivery request is placed!");
    }//GEN-LAST:event_convCompleteBtnActionPerformed
        
        public void displayMyDeliveryRequests(){
            viewTableModel.setRowCount(0);
            RequestDirectory reqDir = appSystem.getReqDir();
            
//        if(this.useraccount.getRole().getRoleType().equals("Convenience Volunteer")){
            for (Map.Entry<String, DeliveryRequest> entry : reqDir.getDeliveryRequests().entrySet()) {

                DeliveryRequest delReq = entry.getValue(); 
                if(delReq.getRequestResponder() == this.useraccount){
                    Object row[] = new Object[4];
                DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
                row[0] = delReq.getRequestID();
                row[1] = delReq.getRequester().getPerson().getName();
                row[2] = format.format(delReq.getRequestDate());
                row[3] = delReq.getStatus();
                 
                viewTableModel.addRow(row);  
                }       
            }
            isService = false;
            isConvenience = false;
            isDelivery = true;
        }
        

        public void displayMyConvenienceRequests(){
            viewTableModel.setRowCount(0);
            RequestDirectory reqDir = appSystem.getReqDir();
             
        for (Map.Entry<String, ConvenienceRequest> entry : reqDir.getConvenienceRequests().entrySet()) {

                ConvenienceRequest convReq = entry.getValue();                            
                Object row[] = new Object[4];
                DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
                row[0] = convReq.getRequestID();
                row[1] = (convReq.getRequester() != null ? convReq.getRequester().getPerson().getName() : null);
                row[2] = format.format(convReq.getRequestDate());
                row[3] = convReq.getStatus();
                 
                viewTableModel.addRow(row);  
                 
            }
        isDelivery = false;
        isService = false;
        isConvenience = true;
        
        }
       
        public void displayMyServiceRequests(){
        viewTableModel.setRowCount(0);
        RequestDirectory reqDir = appSystem.getReqDir();

        for (Map.Entry<String, ServiceRequest> entry : reqDir.getServiceRequests().entrySet()) {
                ServiceRequest serviceReq = entry.getValue();
                 if(serviceReq.getRequestResponder() == this.useraccount){
                 Object row[] = new Object[4];
                DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
                row[0] = serviceReq.getRequestID();
                row[1] = serviceReq.getRequester().getPerson().getName();
                row[2] = format.format(serviceReq.getRequestDate());
                row[3] = serviceReq.getStatus();
                 
                viewTableModel.addRow(row);  
                 }   
            } 
        isDelivery = false;
        isConvenience = false;
        isService = true;
        
    }

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convCompleteBtn;
    private javax.swing.JPanel conveniencePanel;
    private javax.swing.JTextArea convenienceReqResponderComment;
    private javax.swing.JButton createConvenienceRequestBtn;
    private javax.swing.JButton deliveryCompleteBtn;
    private javax.swing.JPanel deliveryPanel;
    private javax.swing.JTextArea deliveryReqResponderComment;
    private javax.swing.JPanel healthPanel;
    private javax.swing.JButton healthReqCompleteBtn;
    private javax.swing.JTextArea healthReqDetails;
    private javax.swing.JTextArea healthResponderComment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel legalAndConnectionPanel;
    private javax.swing.JButton legalConnCompleteBtn;
    private javax.swing.JTextArea legalConnReqDetails;
    private javax.swing.JTextArea legalConnResponderComments;
    private javax.swing.JComboBox<String> prescriptionCombo;
    private javax.swing.JList<String> prescriptionList;
    private javax.swing.JButton removeBtnPrescriptionList;
    private javax.swing.JLabel reqDate;
    private javax.swing.JLabel reqDate1;
    private javax.swing.JLabel reqDate2;
    private javax.swing.JLabel reqDate3;
    private javax.swing.JLabel reqID;
    private javax.swing.JLabel reqID1;
    private javax.swing.JLabel reqID2;
    private javax.swing.JLabel reqID3;
    private javax.swing.JLabel reqLocation;
    private javax.swing.JLabel reqRequester;
    private javax.swing.JLabel reqRequester1;
    private javax.swing.JLabel reqRequester2;
    private javax.swing.JLabel reqRequester3;
    private javax.swing.JLabel reqStatus;
    private javax.swing.JLabel reqStatus1;
    private javax.swing.JLabel reqStatus2;
    private javax.swing.JLabel reqStatus3;
    // End of variables declaration//GEN-END:variables
}
